disabled_rules:
  - identifier_name
  - cyclomatic_complexity
  - function_body_length
  - line_length
  - file_length
  - type_body_length
  - force_cast
  - force_try
  - type_name
opt_in_rules:
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol
  - attributes
  - capture_variable
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - unused_import
  - toggle_bool
  - convenience_type
  - contains_over_filter_count
  - contains_over_first_not_nil
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
excluded:
  - Pods
  - Provenance/Sources/Extensions/IGListKit/IGListSwiftKit
