import Foundation

enum FilterCategory: String, CaseIterable {
    case all = "All"
    case gamesAndSoftware = "games-and-software"
    case carInsuranceAndMaintenance = "car-insurance-and-maintenance"
    case family = "family"
    case groceries = "groceries"
    case booze = "booze"
    case clothingAndAccessories = "clothing-and-accessories"
    case cycling = "cycling"
    case homewareAndAppliances = "homeware-and-appliances"
    case educationAndStudentLoans = "education-and-student-loans"
    case eventsAndGigs = "events-and-gigs"
    case fuel = "fuel"
    case internet = "internet"
    case fitnessAndWellbeing = "fitness-and-wellbeing"
    case hobbies = "hobbies"
    case homeMaintenanceAndImprovements = "home-maintenance-and-improvements"
    case parking = "parking"
    case giftsAndCharity = "gifts-and-charity"
    case holidaysAndTravel = "holidays-and-travel"
    case pets = "pets"
    case publicTransport = "public-transport"
    case hairAndBeauty = "hair-and-beauty"
    case lotteryAndGambling = "lottery-and-gambling"
    case homeInsuranceAndRates = "home-insurance-and-rates"
    case carRepayments = "car-repayments"
    case healthAndMedical = "health-and-medical"
    case pubsAndBars = "pubs-and-bars"
    case rentAndMortgage = "rent-and-mortgage"
    case taxisAndShareCars = "taxis-and-share-cars"
    case investments = "investments"
    case restaurantsAndCafes = "restaurants-and-cafes"
    case tollRoads = "toll-roads"
    case utilities = "utilities"
    case lifeAdmin = "life-admin"
    case takeaway = "takeaway"
    case mobilePhone = "mobile-phone"
    case tobaccoAndVaping = "tobacco-and-vaping"
    case newsMagazinesAndBooks = "news-magazines-and-books"
    case tvAndMusic = "tv-and-music"
    case adult = "adult"
    case technology = "technology"
}
